name = "oauth"
main = "src/index.js"
compatibility_date = "2023-02-04"

kv_namespaces = [
{ binding = "USERS", id = "local", preview_id = "local" },
{ binding = "CODES", id = "local", preview_id = "local" },
{ binding = "CLIENT", id = "local", preview_id = "local" },
{ binding = "TOKENS", id = "local", preview_id = "local" }
]

# Use 'npm run create:key-pair' to gain a valid key pair. Make sure to set the signing key as a secret using 'wrangler secert put SIGNING_KEY'. Never expose your private key!
[env.production.vars]
PUBLIC_KEY=""

[env.production]
kv_namespaces = [
{ binding = "USERS", id = "SOME_KV_ID" },
{ binding = "CODES", id = "SOME_KV_ID" },
{ binding = "CLIENT", id = "SOME_KV_ID" },
{ binding = "TOKENS", id = "SOME_KV_ID" }
]
