name = "oauth"
main = "src/index.js"
compatibility_date = "2023-02-04"

[[env.local.d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "847754d0-d7ed-4fb5-802d-aba6b4478028"

[env.local.vars]
ENVIRONMENT = "local"

[env.production]
name = "oauth"

[[env.local.d1_databases]]
binding = "DB"
database_name = "oauth-db"
database_id = "SOME_DATABASE_ID"

# Use `npm run create:key-pair` to gain a valid key pair. Make sure to set the signing key as a secret using `wrangler secert put SIGNING_KEY`. Never expose your private key!
[env.production.vars]
PUBLIC_KEY = ""
TOKEN_TIME_TO_LIVE = 3600
REFRESH_TOKEN_TIME_TO_LIVE = 21600
