name = "oauth"
main = "src/index.js"
compatibility_date = "2023-02-04"

[[env.local.d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "847754d0-d7ed-4fb5-802d-aba6b4478028"

[env.local.vars]
ENVIRONMENT = "local"
USER_INFO_API_URL = "http://localhost:8787/me"
TOKEN_TIME_TO_LIVE = 3600
REFRESH_TOKEN_TIME_TO_LIVE = 21600
# Use `npm run create:key-pair` to gain a valid key pair.
SIGNING_KEY = ''
PUBLIC_KEY = ''

[env.production]
name = "oauth"

[[env.production.d1_databases]]
binding = "DB"
database_name = "oauth-db"
database_id = "SOME_DATABASE_ID"

[env.production.vars]
ENVIRONMENT = "production"
USER_INFO_API_URL = ""
TOKEN_TIME_TO_LIVE = 3600
REFRESH_TOKEN_TIME_TO_LIVE = 21600
# Use `npm run create:key-pair` to gain a valid key pair. Make sure to set the signing key as a secret using `wrangler secert put SIGNING_KEY`. 
# Never expose your private key (e.g. never commit this file)!
PUBLIC_KEY = ""
